---
# file: roles/workstations-school/tasks/ipa-lesbg.yml

- name: install lizardfs-client
  dnf: name=lizardfs-client state=installed
  tags:
   - setup
   - accounts
   - ipa

- name: install LizardFS IPA config file
  copy: src=lesbg/mfsmount-netshare.cfg dest=/var/tmp/ mode=0600
  tags:
   - setup
   - atomic-setup
   - accounts
   - ipa

- name: create LizardFS IPA mount point
  file: path=/tmp/autojoin
        state=directory
        mode=0755
  tags:
   - setup
   - atomic-setup
   - accounts
   - ipa

- name: mount location to access script
  command: mfsmount -c /var/tmp/mfsmount-netshare.cfg /tmp/autojoin
  tags:
   - setup
   - atomic-setup
   - accounts
   - ipa

- name: join LESB&G FreeIPA domain
  command: /tmp/autojoin/networld/hd_images/linux/f{{ ansible_distribution_major_version|int }}/autojoin.sh
  tags:
   - setup
   - atomic-setup
   - accounts
   - ipa

- name: umount script location
  command: umount /tmp/autojoin
  tags:
   - setup
   - atomic-setup
   - accounts
   - ipa

- name: remove LizardFS IPA config file
  file: name=/var/tmp/mfsmount-netshare.cfg state=absent
  tags:
   - setup
   - atomic-setup
   - accounts
   - ipa
