---
# file: roles/common/tasks/main.yml

- name: be sure ntp and ntpdate are installed
  dnf: name=ntp state=installed
  tags:
   - install
   - ntp
 
#- name: be sure ntp is configured
#  template: src=ntp.conf.j2 dest=/etc/ntp.conf
#  notify:
#    - restart ntpd
#  tags: ntp

- name: be sure ntpd is enabled
  systemd: name=ntpd.service enabled=yes
  tags:
   - install
   - atomic
   - ntp

- name: be sure ntpd is running
  systemd: name=ntpd state=running
  ignore_errors: yes
  tags:
   - install
   - atomic
   - ntp

- name: be sure ntpdate is enabled
  systemd: name=ntpdate.service enabled=yes
  tags:
   - install
   - atomic
   - ntp

